name: dart_mmd
description: Tools and Utilities for parsing and viewing MikuMikuDance formats.
version: 0.0.1
repository: https://github.com/sr229/dart_mmd

environment:
  sdk: '>=3.1.0 <4.0.0'

dev_dependencies:
  melos: ^6.1.0
