name: dart_mmd_parser
description: A PMX/VMD parser for Dart.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.1.0 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
dependencies:
  utf_convert: ^0.10.0+1
